# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828f62c895fa3cc1174ccb38a727428708671912f54aebc9f4284f5398c25d646011d826509461dbe6fb16e59c21cd31cb60672300f339d0e68e67dd1ba45803

test:
  secret_key_base: 86e4a4d03715e4dd425d0a4fc4081eab9663f00f2a130141fe54d83be47d300beea0bd4c7fb45a01656931a63606ad8b7a21eeaedcb3561456ed7750db064168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
